import {ensureTransitions,defaultTransition,compileEditorNav} from './tour-edit-model.js';
import {wrapDegrees,panoramaUForHeading,mapYawToward} from './pano-calibration.js';
export function createTransitionEditor({getModel,getNode,checkpoint,save,photoUrl,base,onChange}){
 const panel=document.createElement('section');panel.id='transitionEditor';panel.innerHTML=`<h2>이 시점의 이동 화살표</h2><p>출발 사진에서 화살표를 끌어 배치하고, 아래 목적지 사진에서 도착 후 볼 부분을 고르세요. 반대 방향 이동은 별도로 설정합니다.</p><div class="transitionRow"><select id="transitionSelect" aria-label="편집할 이동 화살표"></select><label><input id="editArrows" type="checkbox">사진 위 화살표 배치</label></div><div class="transitionRow"><select id="newDestination" aria-label="추가할 목적지"></select><button id="addTransition">이동 버튼 추가</button></div><div id="transitionDetails"><div class="transitionRow"><label>버튼 이름<input id="transitionLabel"></label><label>화살표 아이콘 회전<input id="arrowRotation" type="range" min="-180" max="180" step="1"></label><button id="removeTransition">이 이동 버튼 삭제</button></div><div class="transitionRow"><label>출발 사진 좌우 각도<input id="departureYaw" type="number" min="-180" max="180" step="1"></label><label>출발 사진 위아래 각도<input id="departurePitch" type="number" min="-85" max="85" step="1"></label></div><h3 id="arrivalTitle"></h3><label><input id="preserveArrival" type="checkbox">이동 전 바라보던 방향 유지</label><p>아래 사진의 사각형을 움직이면 도착 방향을 고정합니다.</p><div id="arrivalSurface"><img id="arrivalImage" draggable="false" alt="도착 시점 파노라마"><div id="arrivalWindow"></div><div id="arrivalWindowWrap"></div></div><div class="transitionRow"><label>도착 시 지도 방향<input id="arrivalYaw" type="range" min="-180" max="180" step="1"></label><label>도착 시 위아래 각도<input id="arrivalPitch" type="range" min="-85" max="85" step="1"></label><output id="arrivalAngles"></output></div><p>도착 방향 지도 · 목적지에서 바라볼 쪽을 클릭하세요.</p><div id="arrivalMap"><img src="/spaces/wolhajeong/spatial-map.png" alt="도착 방향 지도" draggable="false"><svg id="arrivalMapOverlay" viewBox="0 0 1952 1277" aria-label="지도에서 도착 방향 선택"></svg></div><p id="transitionSummary"></p></div><button id="previewTransitions">현재 편집본으로 이동 테스트 ↗</button>`;
 document.querySelector('#photoCard').append(panel);const $=s=>panel.querySelector(s);const surface=document.querySelector('#photoSurface');const layer=document.createElement('div');layer.id='transitionMarkers';surface.append(layer);
 let selectedTo=null,fromId=null,activeDrag=null;
 function transition(){const n=getNode();return getModel().transitions?.find(t=>t.from===n?.id&&t.to===selectedTo&&t.enabled!==false)}
 function destination(){return getModel().nodes.find(n=>n.id===selectedTo)}
 function changed(){save();render();onChange?.();document.querySelector('#undo').disabled=false;}
 function markers(){layer.replaceChildren();const from=getNode();if(!from)return;for(const t of getModel().transitions.filter(t=>t.from===from.id&&t.enabled!==false)){
  const b=document.createElement('button');b.type='button';b.dataset.to=t.to;b.className='transitionMarker'+(t.to===selectedTo?' selected':'');b.setAttribute('aria-label',`${t.label} 화살표 배치`);b.style.left=`${((.5-t.yawDeg/360+1)%1)*100}%`;b.style.top=`${(90-t.pitchDeg)/180*100}%`;const icon=document.createElement('span');icon.textContent='↑';icon.style.transform=`rotate(${t.arrowRotationDeg||0}deg)`;const label=document.createElement('small');label.textContent=t.label;b.append(icon,label);layer.append(b);
  b.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();selectedTo=t.to;$('#editArrows').checked=true;checkpoint();activeDrag={kind:'departure',pointer:e.pointerId};surface.setPointerCapture(e.pointerId);render()});
 }}
 function render(){const n=getNode();panel.hidden=!n;layer.hidden=!n;if(!n)return;ensureTransitions(getModel());if(fromId!==n.id){fromId=n.id;selectedTo=null;}const routes=getModel().transitions.filter(t=>t.from===n.id&&t.enabled!==false);if(!routes.some(t=>t.to===selectedTo))selectedTo=routes[0]?.to||null;
  $('#transitionSelect').replaceChildren();for(const t of routes){const o=document.createElement('option');o.value=t.to;o.textContent=`${n.label} → ${t.label}`;$('#transitionSelect').append(o)}$('#transitionSelect').value=selectedTo||'';
  const previous=$('#newDestination').value;$('#newDestination').replaceChildren();for(const p of getModel().nodes.filter(p=>p.id!==n.id&&!routes.some(t=>t.to===p.id))){const o=document.createElement('option');o.value=p.id;o.textContent=`시점 ${p.pointNumber||p.label} · ${p.label}`;$('#newDestination').append(o)}if([...$('#newDestination').options].some(o=>o.value===previous))$('#newDestination').value=previous;
  const t=transition();$('#transitionDetails').hidden=!t;markers();if(!t)return;
  $('#transitionLabel').value=t.label;$('#arrowRotation').value=t.arrowRotationDeg;$('#departureYaw').value=t.yawDeg.toFixed(1);$('#departurePitch').value=t.pitchDeg.toFixed(1);$('#preserveArrival').checked=t.preserveHeading;$('#arrivalYaw').value=t.arrivalYawDeg;$('#arrivalPitch').value=t.arrivalPitchDeg;
  const dest=destination();$('#arrivalTitle').textContent=`도착: 시점 ${dest.pointNumber||dest.label} · ${dest.label}`;const url=photoUrl(dest);$('#arrivalSurface').hidden=!url;if(url&&$('#arrivalImage').getAttribute('src')!==url)$('#arrivalImage').src=url;
  const [mx,my]=dest.mapPosition,angle=t.arrivalYawDeg*Math.PI/180;
  $('#arrivalMapOverlay').innerHTML=`<path d="M ${mx} ${my} L ${mx-Math.sin(angle-.35)*220} ${my-Math.cos(angle-.35)*220} L ${mx-Math.sin(angle+.35)*220} ${my-Math.cos(angle+.35)*220} Z" fill="#ffb22e88"/><circle cx="${mx}" cy="${my}" r="20" fill="#ffb22e" stroke="white" stroke-width="6"/>`;
  const u=panoramaUForHeading(dest.imageYawDeg||0,t.arrivalYawDeg),left=u*100-7.03125;const top=(90-t.arrivalPitchDeg)/180*100-25;
  for(const id of ['arrivalWindow','arrivalWindowWrap']){$('#'+id).style.top=`${top}%`;$('#'+id).style.opacity=t.preserveHeading?'.35':'1';}
  $('#arrivalWindow').style.left=`${left}%`;const wrap=left<0?left+100:left+14.0625>100?left-100:null;$('#arrivalWindowWrap').hidden=wrap===null;if(wrap!==null)$('#arrivalWindowWrap').style.left=`${wrap}%`;
  $('#arrivalAngles').textContent=`지도 ${Math.round(t.arrivalYawDeg)}° / 위아래 ${Math.round(t.arrivalPitchDeg)}°`;
  $('#transitionSummary').textContent=`${n.label}에서 ‘${t.label}’ 버튼 → ${dest.label} 도착 · ${t.preserveHeading?'기존 시선 유지':'지도 '+Math.round(t.arrivalYawDeg)+'° 방향으로 보기'}`;
 }
 $('#arrivalMapOverlay').onpointerdown=e=>{const t=transition(),dest=destination();if(!t||!dest)return;const r=e.currentTarget.getBoundingClientRect();checkpoint();t.preserveHeading=false;t.arrivalYawDeg=mapYawToward(dest.mapPosition,[(e.clientX-r.left)/r.width*1952,(e.clientY-r.top)/r.height*1277]);changed()};
 $('#transitionSelect').onchange=e=>{selectedTo=e.target.value;render()};
 $('#addTransition').onclick=()=>{const from=getNode(),to=getModel().nodes.find(n=>n.id===$('#newDestination').value);if(!from||!to)return;checkpoint();const m=getModel();if(!m.edges.some(e=>e.includes(from.id)&&e.includes(to.id)))m.edges.push([from.id,to.id]);m.transitions ||= [];const t=m.transitions.find(t=>t.from===from.id&&t.to===to.id);if(t)t.enabled=true;else m.transitions.push(defaultTransition(from,to));if(!m.transitions.some(t=>t.from===to.id&&t.to===from.id))m.transitions.push({...defaultTransition(to,from),enabled:false});selectedTo=to.id;changed()};
 $('#removeTransition').onclick=()=>{const t=transition();if(t){checkpoint();t.enabled=false;changed()}};
 for(const [id,key]of [['transitionLabel','label'],['arrowRotation','arrowRotationDeg'],['departureYaw','yawDeg'],['departurePitch','pitchDeg'],['arrivalYaw','arrivalYawDeg'],['arrivalPitch','arrivalPitchDeg']])$('#'+id).onchange=e=>{const t=transition();if(!t)return;const value=key==='label'?e.target.value.trim():Number(e.target.value);if(key!=='label'&&!Number.isFinite(value))return;checkpoint();t[key]=key==='label'?value||destination().label:Math.max(key.toLowerCase().includes('pitch')?-85:-180,Math.min(key.toLowerCase().includes('pitch')?85:180,value));if(key.startsWith('arrival'))t.preserveHeading=false;changed()};
 $('#preserveArrival').onchange=e=>{const t=transition();if(t){checkpoint();t.preserveHeading=e.target.checked;changed()}};
 function move(e,kind){const t=transition();if(!t)return;const target=kind==='arrival'?$('#arrivalSurface'):surface,r=target.getBoundingClientRect();const u=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),v=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));if(kind==='arrival'){t.preserveHeading=false;t.arrivalYawDeg=wrapDegrees((destination().imageYawDeg||0)+180-u*360);t.arrivalPitchDeg=Math.max(-85,Math.min(85,90-v*180));}else{t.yawDeg=wrapDegrees(180-u*360);t.pitchDeg=Math.max(-85,Math.min(85,90-v*180));}render();}
 surface.addEventListener('pointerdown',e=>{if(e.button!==0)return;const marker=e.target.closest('.transitionMarker');if(marker){selectedTo=marker.dataset.to;$('#editArrows').checked=true;}if(!$('#editArrows').checked||!transition())return;e.stopImmediatePropagation();e.preventDefault();checkpoint();activeDrag={kind:'departure',pointer:e.pointerId};surface.setPointerCapture(e.pointerId);move(e,'departure')},true);
 surface.addEventListener('pointermove',e=>{if(activeDrag?.kind==='departure'){e.stopImmediatePropagation();move(e,'departure')}},true);
 $('#arrivalSurface').onpointerdown=e=>{if(e.button!==0)return;checkpoint();activeDrag={kind:'arrival',pointer:e.pointerId};e.currentTarget.setPointerCapture(e.pointerId);move(e,'arrival')};$('#arrivalSurface').onpointermove=e=>{if(activeDrag?.kind==='arrival')move(e,'arrival')};
 for(const target of [surface,$('#arrivalSurface')])for(const event of ['pointerup','pointercancel'])target.addEventListener(event,e=>{if(activeDrag){e.stopImmediatePropagation();activeDrag=null;changed()}},true);
 $('#previewTransitions').onclick=()=>{const n=getNode();if(!n)return;const nav=compileEditorNav(getModel(),base);nav.start=n.id;localStorage.setItem('splattour-editor-preview',JSON.stringify(nav));window.open(`/pano.html?space=wolhajeong&editorPreview=1&node=${encodeURIComponent(n.id)}`,'_blank')};
 return {render};
}
